---
title: "groupproject"
output: html_document
date: "2024-12-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
```


```{r}
library(tidyverse)
library(plyr)
library(lme4)
library(plotfunctions)
library(dplyr)
library(Amelia)
library(tidyr)
library(corrplot)
library(ggplot2)
library(performance)
```
```{r}
setwd("C:/Users/Thanos/Desktop/Advanced Machine Learning/group project")
```
```{r}
rstudioapi::filesPaneNavigate("C:/Users/Thanos/Desktop/Advanced Machine Learning/group project")
```

```{r}
read.csv("students_mental_health_survey.csv")

```

```{r}
str(students_mental_health_survey)
summary(students_mental_health_survey)
```

So the data table has very few missing values, however because later on I encountered some error due to the uneven length of the collumns I decided to weed the records with missing values out.

```{r}
col_na_count <- colSums(is.na(students_mental_health_survey))
print(col_na_count, max = length(col_na_count))
```
Don't bother with the missmap, it turns out I was trying to find something that isn't even there, I believe the NA values were so few that missmap function can't show much detail
```{r}
missmap(students_mental_health_survey, main = "Missing Values Map", col = c("red", "blue"))

```